"""initial schema

Revision ID: 487258e661ec
Revises: 
Create Date: 2026-08-14 18:39:10.438238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.models.base

# revision identifiers, used by Alembic.
revision: str = '487258e661ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_families',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('defining_dna_signature', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('member_genome_ids', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('performance_summary', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_production_plans',
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('target_final_designs', sa.Integer(), nullable=False),
    sa.Column('portfolio_allocation', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('collections', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('experimental_slots', sa.Integer(), nullable=False),
    sa.Column('winner_mutation_slots', sa.Integer(), nullable=False),
    sa.Column('production_slots', sa.Integer(), nullable=False),
    sa.Column('budget_cap_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.String(length=4000), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_production_plans_plan_date'), 'daily_production_plans', ['plan_date'], unique=True)
    op.create_table('experiments',
    sa.Column('hypothesis', sa.String(length=2000), nullable=False),
    sa.Column('design_genome_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('collection_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('variables_tested', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('output_candidate_ids', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scores_summary', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('winner_candidate_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('failure_summary', sa.String(length=2000), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('commercial_outcome', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_collection_id'), 'experiments', ['collection_id'], unique=False)
    op.create_index(op.f('ix_experiments_design_genome_id'), 'experiments', ['design_genome_id'], unique=False)
    op.create_table('provider_health_logs',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=200), nullable=True),
    sa.Column('circuit_state', sa.String(length=20), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_health_logs_provider'), 'provider_health_logs', ['provider'], unique=False)
    op.create_table('collections',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('thesis', sa.String(length=2000), nullable=False),
    sa.Column('target_aesthetic', sa.String(length=500), nullable=False),
    sa.Column('target_customer_hypothesis', sa.String(length=1000), nullable=False),
    sa.Column('palette_boundaries', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('medium', sa.String(length=100), nullable=False),
    sa.Column('subject_families', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('composition_diversity_requirements', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('target_design_count', sa.Integer(), nullable=False),
    sa.Column('experimental_variables', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('creative_family_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creative_family_id'], ['creative_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_events',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('generation_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('processing_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('collection_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('design_genome_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('generation_candidate_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_events_collection_id'), 'cost_events', ['collection_id'], unique=False)
    op.create_index(op.f('ix_cost_events_provider'), 'cost_events', ['provider'], unique=False)
    op.create_table('design_genomes',
    sa.Column('design_lineage_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_genome_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('derived_from_version_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('collection_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('subject_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('style_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('composition_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('palette_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('texture_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('medium_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('era_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('mood_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('detail_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('print_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('commercial_dna', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('mutation_map', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['derived_from_version_id'], ['design_genomes.id'], ),
    sa.ForeignKeyConstraint(['parent_genome_id'], ['design_genomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_genomes_collection_id'), 'design_genomes', ['collection_id'], unique=False)
    op.create_index(op.f('ix_design_genomes_design_lineage_id'), 'design_genomes', ['design_lineage_id'], unique=False)
    op.create_index(op.f('ix_design_genomes_parent_genome_id'), 'design_genomes', ['parent_genome_id'], unique=False)
    op.create_table('concepts',
    sa.Column('design_genome_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('collection_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('production_mode', sa.String(length=20), nullable=False),
    sa.Column('planned_candidate_count', sa.Integer(), nullable=False),
    sa.Column('gate_status', sa.String(length=20), nullable=False),
    sa.Column('gate_reasoning', sa.String(length=2000), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['design_genome_id'], ['design_genomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_collection_id'), 'concepts', ['collection_id'], unique=False)
    op.create_index(op.f('ix_concepts_design_genome_id'), 'concepts', ['design_genome_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('concept_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('compiled_prompt', sa.String(length=4000), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=300), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_concept_id'), 'generation_jobs', ['concept_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_idempotency_key'), 'generation_jobs', ['idempotency_key'], unique=True)
    op.create_table('generation_candidates',
    sa.Column('generation_job_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('concept_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('design_genome_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_repair', sa.Boolean(), nullable=False),
    sa.Column('repair_attempt_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['design_genome_id'], ['design_genomes.id'], ),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_candidates_concept_id'), 'generation_candidates', ['concept_id'], unique=False)
    op.create_index(op.f('ix_generation_candidates_design_genome_id'), 'generation_candidates', ['design_genome_id'], unique=False)
    op.create_index(op.f('ix_generation_candidates_generation_job_id'), 'generation_candidates', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_generation_candidates_perceptual_hash'), 'generation_candidates', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_generation_candidates_status'), 'generation_candidates', ['status'], unique=False)
    op.create_table('approvals',
    sa.Column('generation_candidate_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('resulting_genome_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_candidate_id'], ['generation_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_generation_candidate_id'), 'approvals', ['generation_candidate_id'], unique=False)
    op.create_table('artworks',
    sa.Column('generation_candidate_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('design_genome_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('collection_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('master_storage_key', sa.String(length=500), nullable=False),
    sa.Column('master_width_px', sa.Integer(), nullable=False),
    sa.Column('master_height_px', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['design_genome_id'], ['design_genomes.id'], ),
    sa.ForeignKeyConstraint(['generation_candidate_id'], ['generation_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_artworks_collection_id'), 'artworks', ['collection_id'], unique=False)
    op.create_index(op.f('ix_artworks_design_genome_id'), 'artworks', ['design_genome_id'], unique=False)
    op.create_index(op.f('ix_artworks_generation_candidate_id'), 'artworks', ['generation_candidate_id'], unique=True)
    op.create_table('evaluations',
    sa.Column('generation_candidate_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('scored_by', sa.String(length=100), nullable=False),
    sa.Column('aesthetic', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('originality', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('commercial_potential', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('technical_quality', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('printability', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('collection_fit', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('diversity', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('overall_pass', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_candidate_id'], ['generation_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_generation_candidate_id'), 'evaluations', ['generation_candidate_id'], unique=False)
    op.create_table('failure_records',
    sa.Column('generation_candidate_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('failure_class', sa.String(length=30), nullable=False),
    sa.Column('detected_problems', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('diagnosis_reasoning', sa.String(length=2000), nullable=False),
    sa.Column('diagnosed_by', sa.String(length=100), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_candidate_id'], ['generation_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_records_failure_class'), 'failure_records', ['failure_class'], unique=False)
    op.create_index(op.f('ix_failure_records_generation_candidate_id'), 'failure_records', ['generation_candidate_id'], unique=False)
    op.create_table('commercial_observations',
    sa.Column('artwork_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('design_genome_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('external_listing_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['design_genome_id'], ['design_genomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_observations_artwork_id'), 'commercial_observations', ['artwork_id'], unique=False)
    op.create_index(op.f('ix_commercial_observations_design_genome_id'), 'commercial_observations', ['design_genome_id'], unique=False)
    op.create_table('etsy_listing_packages',
    sa.Column('artwork_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('title_concepts', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('description_data', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('keyword_candidates', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('palette', sa.String(length=100), nullable=False),
    sa.Column('orientation', sa.String(length=20), nullable=False),
    sa.Column('collection_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('internal_sku', sa.String(length=50), nullable=False),
    sa.Column('print_export_ids', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('mockup_ids', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_listing_id', sa.String(length=100), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etsy_listing_packages_artwork_id'), 'etsy_listing_packages', ['artwork_id'], unique=True)
    op.create_table('mockups',
    sa.Column('artwork_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mockups_artwork_id'), 'mockups', ['artwork_id'], unique=False)
    op.create_table('print_exports',
    sa.Column('artwork_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('ratio', sa.String(length=10), nullable=False),
    sa.Column('target_long_edge_px', sa.Integer(), nullable=False),
    sa.Column('actual_width_px', sa.Integer(), nullable=False),
    sa.Column('actual_height_px', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('upscaled', sa.Boolean(), nullable=False),
    sa.Column('upscale_provider', sa.String(length=100), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_exports_artwork_id'), 'print_exports', ['artwork_id'], unique=False)
    op.create_table('repair_attempts',
    sa.Column('failure_record_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('genome_delta', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_delta', sa.String(length=2000), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('resulting_candidate_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('cost_event_id', app.db.models.base.GUID(), nullable=True),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cost_event_id'], ['cost_events.id'], ),
    sa.ForeignKeyConstraint(['failure_record_id'], ['failure_records.id'], ),
    sa.ForeignKeyConstraint(['resulting_candidate_id'], ['generation_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_attempts_failure_record_id'), 'repair_attempts', ['failure_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_attempts_failure_record_id'), table_name='repair_attempts')
    op.drop_table('repair_attempts')
    op.drop_index(op.f('ix_print_exports_artwork_id'), table_name='print_exports')
    op.drop_table('print_exports')
    op.drop_index(op.f('ix_mockups_artwork_id'), table_name='mockups')
    op.drop_table('mockups')
    op.drop_index(op.f('ix_etsy_listing_packages_artwork_id'), table_name='etsy_listing_packages')
    op.drop_table('etsy_listing_packages')
    op.drop_index(op.f('ix_commercial_observations_design_genome_id'), table_name='commercial_observations')
    op.drop_index(op.f('ix_commercial_observations_artwork_id'), table_name='commercial_observations')
    op.drop_table('commercial_observations')
    op.drop_index(op.f('ix_failure_records_generation_candidate_id'), table_name='failure_records')
    op.drop_index(op.f('ix_failure_records_failure_class'), table_name='failure_records')
    op.drop_table('failure_records')
    op.drop_index(op.f('ix_evaluations_generation_candidate_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_artworks_generation_candidate_id'), table_name='artworks')
    op.drop_index(op.f('ix_artworks_design_genome_id'), table_name='artworks')
    op.drop_index(op.f('ix_artworks_collection_id'), table_name='artworks')
    op.drop_table('artworks')
    op.drop_index(op.f('ix_approvals_generation_candidate_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_generation_candidates_status'), table_name='generation_candidates')
    op.drop_index(op.f('ix_generation_candidates_perceptual_hash'), table_name='generation_candidates')
    op.drop_index(op.f('ix_generation_candidates_generation_job_id'), table_name='generation_candidates')
    op.drop_index(op.f('ix_generation_candidates_design_genome_id'), table_name='generation_candidates')
    op.drop_index(op.f('ix_generation_candidates_concept_id'), table_name='generation_candidates')
    op.drop_table('generation_candidates')
    op.drop_index(op.f('ix_generation_jobs_idempotency_key'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_concept_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_concepts_design_genome_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_collection_id'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_design_genomes_parent_genome_id'), table_name='design_genomes')
    op.drop_index(op.f('ix_design_genomes_design_lineage_id'), table_name='design_genomes')
    op.drop_index(op.f('ix_design_genomes_collection_id'), table_name='design_genomes')
    op.drop_table('design_genomes')
    op.drop_index(op.f('ix_cost_events_provider'), table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_collection_id'), table_name='cost_events')
    op.drop_table('cost_events')
    op.drop_table('collections')
    op.drop_index(op.f('ix_provider_health_logs_provider'), table_name='provider_health_logs')
    op.drop_table('provider_health_logs')
    op.drop_index(op.f('ix_experiments_design_genome_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_collection_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_daily_production_plans_plan_date'), table_name='daily_production_plans')
    op.drop_table('daily_production_plans')
    op.drop_table('creative_families')
    # ### end Alembic commands ###
