"""add getvela export tables

Revision ID: 4b7488e7bfc6
Revises: 645cf6c66525
Create Date: 2026-08-15 09:42:37.045606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.models.base


# revision identifiers, used by Alembic.
revision: str = '4b7488e7bfc6'
down_revision: Union[str, None] = '645cf6c66525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('getvela_export_batches',
    sa.Column('requested_by', sa.String(length=200), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('getvela_export_records',
    sa.Column('batch_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('artwork_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['getvela_export_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_getvela_export_records_artwork_id'), 'getvela_export_records', ['artwork_id'], unique=True)
    op.create_index(op.f('ix_getvela_export_records_batch_id'), 'getvela_export_records', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_getvela_export_records_batch_id'), table_name='getvela_export_records')
    op.drop_index(op.f('ix_getvela_export_records_artwork_id'), table_name='getvela_export_records')
    op.drop_table('getvela_export_records')
    op.drop_table('getvela_export_batches')
    # ### end Alembic commands ###
