"""add market_signals table

Revision ID: 645cf6c66525
Revises: f2dbde17231f
Create Date: 2026-08-14 20:45:39.368212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.models.base


# revision identifiers, used by Alembic.
revision: str = '645cf6c66525'
down_revision: Union[str, None] = 'f2dbde17231f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_signals',
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_signals_source'), 'market_signals', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_signals_source'), table_name='market_signals')
    op.drop_table('market_signals')
    # ### end Alembic commands ###
