"""add drive archive table

Revision ID: a02ab355cd5b
Revises: 4b7488e7bfc6
Create Date: 2026-08-15 10:17:41.527951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.models.base


# revision identifiers, used by Alembic.
revision: str = 'a02ab355cd5b'
down_revision: Union[str, None] = '4b7488e7bfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_archive_records',
    sa.Column('artwork_id', app.db.models.base.GUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('drive_file_id', sa.String(length=200), nullable=False),
    sa.Column('drive_file_url', sa.String(length=1000), nullable=False),
    sa.Column('id', app.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_archive_records_artwork_id'), 'drive_archive_records', ['artwork_id'], unique=True)
    op.create_index(op.f('ix_drive_archive_records_sku'), 'drive_archive_records', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drive_archive_records_sku'), table_name='drive_archive_records')
    op.drop_index(op.f('ix_drive_archive_records_artwork_id'), table_name='drive_archive_records')
    op.drop_table('drive_archive_records')
    # ### end Alembic commands ###
