"""add elimination_reason to generation_candidates

Revision ID: a4d6beb7b0b4
Revises: 487258e661ec
Create Date: 2026-08-14 18:52:32.683562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d6beb7b0b4'
down_revision: Union[str, None] = '487258e661ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_candidates', sa.Column('elimination_reason', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_candidates', 'elimination_reason')
    # ### end Alembic commands ###
